name: Sync

on:
  push:
    branches:
      - master

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.SYNC_TOKEN }}
      - name: Sync Repos
        run: ./scripts/sync.sh
        env:
          BEFORE_SHA: ${{ github.event.before }}
          AFTER_SHA: ${{ github.event.after }}
  release_draft_one:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter-one.yml
          name: one
          tag: vone
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  release_draft_two:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter-two.yml
          name: two
          tag: vtwo
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}